WORDS = [
    # Tiere
    "ADLER", "AFFE", "BIENE", "DACHS", "DELFIN", "EICHHÖRNCHEN", "ELEFANT",
    "ENTE", "ESEL", "FALKE", "FISCH", "FROSCH", "FUCHS", "GIRAFFE", "GORILLA",
    "HASE", "HIRSCH", "HUMMEL", "IGEL", "JAGUAR", "KAMEL", "KÄNGURU", "KATZE",
    "KOALA", "KROKODIL", "LEOPARD", "LÖWE", "LUCHS", "MAUS", "MÖWE", "NILPFERD",
    "OKTOPUS", "ORCA", "PANDA", "PAPAGEI", "PFERD", "PINGUIN", "RABE", "SEEHUND",
    "SCHILDKRÖTE", "SCHLANGE", "SCHMETTERLING", "SCHWEIN", "STORCH", "TIGER",
    "TINTENFISCH", "TRUTHAHN", "VOGEL", "WASCHBÄR", "WOLF", "ZEBRA",

    # Natur & Geographie
    "BERG", "FLUSS", "GEBIRGE", "GLETSCHER", "HÖHLE", "INSEL", "KÜSTE", "MEER",
    "OZEAN", "SEE", "STRAND", "TAL", "WALD", "WÜSTE", "VULKAN", "WASSERFALL",
    "REGENWALD", "TUNDRA", "SAVANNE", "STEPPE", "DELTA", "FJORD",

    # Berufe
    "ARZT", "ARCHITEKT", "BÄCKER", "BIBLIOTHEKAR", "CHEMIKER", "DICHTER",
    "ELEKTRIKER", "FORSCHER", "GÄRTNER", "INGENIEUR", "JOURNALIST", "KAUFMANN",
    "KOCH", "LEHRER", "MALER", "MUSIKER", "PILOT", "RICHTER", "SCHNEIDER",
    "TÄNZER", "TIERARZT", "ZIMMERMANN",

    # Essen & Trinken
    "APFEL", "BIRNE", "BANANE", "BLAUBEERE", "BROMBEERE", "ERDBEERE",
    "HIMBEERE", "KIRSCHE", "MANDARINE", "MANGO", "MELONE", "PFLAUME",
    "ANANAS", "GURKE", "KARTOFFEL", "KAROTTE", "KÜRBIS", "PAPRIKA",
    "TOMATE", "ZUCCHINI", "SPAGHETTI", "LASAGNE", "SCHNITZEL", "KNÖDEL",
    "BREZEL", "MARZIPAN", "SCHOKOLADE", "VANILLE", "ZIMT",

    # Technik & Wissenschaft
    "ALGORITHMUS", "ANTENNE", "BATTERIE", "COMPUTER", "DATENBANK", "DRUCKER",
    "ELEKTRONIK", "GENERATOR", "GRAVITITATION", "HALBLEITER", "INTERNET",
    "KATHODE", "LASER", "MIKROSKOP", "NETZWERK", "QUANTENPHYSIK", "ROBOTER",
    "SATELLIT", "SOFTWARE", "TELESKOP", "ULTRASCHALL", "WISSENSCHAFT",

    # Sport & Freizeit
    "BASKETBALL", "BOGENSCHIESSEN", "FECHTEN", "FUSSBALL", "GOLF", "HANDBALL",
    "HOCKEY", "JUDO", "KLETTERN", "LEICHTATHLETIK", "RADSPORT", "REITEN",
    "RUDERN", "SCHACH", "SCHWIMMEN", "SEGELN", "SKIFAHREN", "SURFEN",
    "TISCHTENNIS", "TURNEN", "VOLLEYBALL", "WANDERN",

    # Länder & Städte
    "ARGENTINIEN", "AUSTRALIEN", "BERLIN", "BRASILIEN", "FRANKREICH", "GRIECHENLAND",
    "HAMBURG", "INDIEN", "JAPAN", "KANADA", "MEXIKO", "MÜNCHEN", "NORWEGEN",
    "PORTUGAL", "SCHWEDEN", "SINGAPUR", "SPANIEN", "THAILAND", "TÜRKEI",

    # Allgemein
    "ABENTEUER", "BIBLIOTHEK", "DRACHENFLIEGEN", "ERINNERUNG", "FANTASIE",
    "GEDANKE", "HORIZONT", "INSPIRATION", "JAHRESZEIT", "KREATIVITÄT",
    "LEIDENSCHAFT", "MEISTERWERK", "NEUGIER", "PHANTASIE", "QUERFLÖTE",
    "RÄTSEL", "STIMMUNG", "TRAUMWELT", "UNIVERSUM", "VERWANDLUNG",
    "WINTERGARTEN", "ZAUBEREI",
]
