WORDS_DE = [
    # Tiere
    "ADLER", "AFFE", "BIENE", "DACHS", "DELFIN", "EICHHÖRNCHEN", "ELEFANT",
    "ENTE", "ESEL", "FALKE", "FISCH", "FROSCH", "FUCHS", "GIRAFFE", "GORILLA",
    "HASE", "HIRSCH", "HUMMEL", "IGEL", "JAGUAR", "KAMEL", "KÄNGURU", "KATZE",
    "KOALA", "KROKODIL", "LEOPARD", "LÖWE", "LUCHS", "MAUS", "MÖWE", "NILPFERD",
    "OKTOPUS", "ORCA", "PANDA", "PAPAGEI", "PFERD", "PINGUIN", "RABE", "SEEHUND",
    "SCHILDKRÖTE", "SCHLANGE", "SCHMETTERLING", "SCHWEIN", "STORCH", "TIGER",
    "TINTENFISCH", "TRUTHAHN", "VOGEL", "WASCHBÄR", "WOLF", "ZEBRA",

    # Natur & Geographie
    "BERG", "FLUSS", "GEBIRGE", "GLETSCHER", "HÖHLE", "INSEL", "KÜSTE", "MEER",
    "OZEAN", "SEE", "STRAND", "TAL", "WALD", "WÜSTE", "VULKAN", "WASSERFALL",
    "REGENWALD", "TUNDRA", "SAVANNE", "STEPPE", "DELTA", "FJORD",

    # Berufe
    "ARZT", "ARCHITEKT", "BÄCKER", "BIBLIOTHEKAR", "CHEMIKER", "DICHTER",
    "ELEKTRIKER", "FORSCHER", "GÄRTNER", "INGENIEUR", "JOURNALIST", "KAUFMANN",
    "KOCH", "LEHRER", "MALER", "MUSIKER", "PILOT", "RICHTER", "SCHNEIDER",
    "TÄNZER", "TIERARZT", "ZIMMERMANN",

    # Essen & Trinken
    "APFEL", "BIRNE", "BANANE", "BLAUBEERE", "BROMBEERE", "ERDBEERE",
    "HIMBEERE", "KIRSCHE", "MANDARINE", "MANGO", "MELONE", "PFLAUME",
    "ANANAS", "GURKE", "KARTOFFEL", "KAROTTE", "KÜRBIS", "PAPRIKA",
    "TOMATE", "ZUCCHINI", "SPAGHETTI", "LASAGNE", "SCHNITZEL", "KNÖDEL",
    "BREZEL", "MARZIPAN", "SCHOKOLADE", "VANILLE", "ZIMT",

    # Technik & Wissenschaft
    "ALGORITHMUS", "ANTENNE", "BATTERIE", "COMPUTER", "DATENBANK", "DRUCKER",
    "ELEKTRONIK", "GENERATOR", "GRAVITATION", "HALBLEITER", "INTERNET",
    "KATHODE", "LASER", "MIKROSKOP", "NETZWERK", "QUANTENPHYSIK", "ROBOTER",
    "SATELLIT", "SOFTWARE", "TELESKOP", "ULTRASCHALL", "WISSENSCHAFT",

    # Sport & Freizeit
    "BASKETBALL", "FECHTEN", "FUSSBALL", "GOLF", "HANDBALL",
    "HOCKEY", "JUDO", "KLETTERN", "LEICHTATHLETIK", "RADSPORT", "REITEN",
    "RUDERN", "SCHACH", "SCHWIMMEN", "SEGELN", "SKIFAHREN", "SURFEN",
    "TISCHTENNIS", "TURNEN", "VOLLEYBALL", "WANDERN",

    # Allgemein
    "ABENTEUER", "BIBLIOTHEK", "ERINNERUNG", "FANTASIE",
    "GEDANKE", "HORIZONT", "INSPIRATION", "JAHRESZEIT", "KREATIVITÄT",
    "LEIDENSCHAFT", "MEISTERWERK", "NEUGIER", "RÄTSEL", "STIMMUNG",
    "TRAUMWELT", "UNIVERSUM", "VERWANDLUNG", "WINTERGARTEN", "ZAUBEREI",
]

WORDS_EN = [
    # Animals
    "EAGLE", "MONKEY", "DOLPHIN", "ELEPHANT", "GIRAFFE", "GORILLA",
    "RABBIT", "IGUANA", "JAGUAR", "CAMEL", "KANGAROO", "LEOPARD",
    "OCTOPUS", "PARROT", "PENGUIN", "TURTLE", "BUTTERFLY", "CROCODILE",
    "FLAMINGO", "HEDGEHOG", "JELLYFISH", "PANTHER", "SQUIRREL", "WOLVERINE",

    # Nature & Geography
    "MOUNTAIN", "GLACIER", "ISLAND", "DESERT", "VOLCANO", "WATERFALL",
    "RAINFOREST", "CANYON", "MEADOW", "HORIZON", "AVALANCHE", "PENINSULA",
    "ARCHIPELAGO", "PLATEAU", "SAVANNAH", "TUNDRA", "FJORD", "LAGOON",

    # Professions
    "ARCHITECT", "LIBRARIAN", "CHEMIST", "DETECTIVE", "ENGINEER",
    "JOURNALIST", "MUSICIAN", "SCIENTIST", "SURGEON", "CARPENTER",
    "ASTRONAUT", "BIOLOGIST", "PHARMACIST", "PROFESSOR", "VETERINARIAN",

    # Food & Drink
    "PINEAPPLE", "STRAWBERRY", "BLUEBERRY", "RASPBERRY", "CHOCOLATE",
    "CINNAMON", "AVOCADO", "BROCCOLI", "MUSHROOM", "SPAGHETTI",
    "CROISSANT", "PANCAKE", "GRAPEFRUIT", "WATERMELON", "ARTICHOKE",

    # Science & Technology
    "ALGORITHM", "COMPUTER", "DATABASE", "ELECTRON", "INTERNET",
    "MICROSCOPE", "SATELLITE", "SOFTWARE", "TELESCOPE", "QUANTUM",
    "BLUETOOTH", "HOLOGRAM", "BANDWIDTH", "CYBERNETIC", "FREQUENCY",

    # Sports & Leisure
    "BASKETBALL", "FOOTBALL", "VOLLEYBALL", "SWIMMING", "CLIMBING",
    "ARCHERY", "GYMNASTICS", "SURFING", "BADMINTON", "MARATHON",

    # General
    "ADVENTURE", "BUTTERFLY", "DISCOVERY", "EVOLUTION", "FANTASY",
    "LABYRINTH", "NIGHTMARE", "PARADISE", "SILHOUETTE", "WANDERLUST",
    "SERENDIPITY", "NOSTALGIA", "REBELLION", "EUPHORIA", "SYMPHONY",
]

WORDS = {
    'de': WORDS_DE,
    'en': WORDS_EN,
}
